HouseRentingSystem/Models/ErrorViewModel.cs
namespace HouseRentingSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HouseRentingSystem/Controllers/AgentController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Core.Services;
using HouseRentingSystem.Core.ViewModels.Agent;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using HouseRentingSystem.Attributes;
using static HouseRentingSystem.Core.Constants.MessageConstants;

namespace HouseRentingSystem.Controllers
{

    public class AgentController : BaseController
    {
        //Injecting the needed service to the controller before using it afterwards
        private readonly IAgentService _agentService;
        public AgentController(IAgentService agentService)
        {
            _agentService = agentService;
        }

        [HttpGet]
        [NotAnAgent]
        public IActionResult Become()
        {

            var model = new BecomeAgentFormModel();
            return View(model);
        }

        [HttpPost]
        [NotAnAgent]
        public async Task<IActionResult> Become(BecomeAgentFormModel model)
        {

            if (await _agentService.UserWithPhoneNumberExistsAsync(model.PhoneNumber)) { }
            {
                ModelState.AddModelError(nameof(model.PhoneNumber), PhoneExists);
            }

            if (await _agentService.UserHasRentsAsync(User.Id()))
            {
                ModelState.AddModelError("Error", HasRent);
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await _agentService.CreateAsync(User.Id(), model.PhoneNumber);

            return RedirectToAction(nameof(HouseController.All), "Houses");
        }
    }
}

HouseRentingSystem/Controllers/BaseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Controllers
{
    [Authorize]
    public class BaseController : Controller
    {


    }
}

HouseRentingSystem/Controllers/HomeController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Core.ViewModels.Home;
using HouseRentingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HouseRentingSystem.Controllers
{
    public class HomeController : BaseController
    {
        //Injecing the needed service to the controller before using it afterwards

        private readonly ILogger<HomeController> _logger;
        private readonly IHouseService _houseService;
        public HomeController(ILogger<HomeController> logger, IHouseService houseService)
        {
            _logger = logger;
            _houseService = houseService;
        }

        [AllowAnonymous] // cause HomeCTR inherits BaseCTR which is AUTHORIZED 
        public async Task<IActionResult> Index()
        {
            var model = await _houseService.LastThreeHousesAsync();
            return View(model);
        }


        [AllowAnonymous] // cause HomeCTR inherits BaseCTR which is AUTHORIZED 

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HouseRentingSystem/Controllers/HouseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using HouseRentingSystem.Core.ViewModels.House;
using HouseRentingSystem.Core.Contracts;
using System.Security.Claims;
using HouseRentingSystem.Attributes;

namespace HouseRentingSystem.Controllers
{

    public class HouseController : BaseController
    {
        //implementing the service in the HOUSE CONTROLLER

        private readonly IHouseService houseService;
        private readonly IAgentService agentService;
        public HouseController(IHouseService _houseService, IAgentService _agentService)
        {
            houseService = _houseService;
            agentService = _agentService;

        }
        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            var model = new AllHousesQueryModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Mine()
        {
            var model = new AllHousesQueryModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Details(int id)
        {
            var model = new HouseDetailsViewModel();
            return View(model);
        }

        [HttpGet]
        [MustBeAgent]
        public async Task<IActionResult> Add()
        {

            var model = new HouseFormModel()
            {
                Categories = await houseService.AllCategoriesAsync()
            };

            return View();
        }

        [HttpPost]
        [MustBeAgent]
        public async Task<IActionResult> Add(HouseFormModel model)
        {
            if (await houseService.CategoryExistsAsync(model.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "");
            }

            if (ModelState.IsValid == false)
            {
                model.Categories = await houseService.AllCategoriesAsync();
                return View(model);
            }

            int? agentId = await agentService.GetAgentIdAsync(User.Id());

            int newHouseId = await houseService.CreateAsync(model, agentId ?? 0);

            return RedirectToAction(nameof(Details), new { id = newHouseId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = new HouseFormModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, HouseFormModel model)
        {

            return RedirectToAction(nameof(Details), new { id = 1 });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = new HouseDetailsViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(HouseDetailsViewModel model)
        {

            return RedirectToAction(nameof(All));
        }


        [HttpPost]
        public async Task<IActionResult> Rent(int id)
        {
            return RedirectToAction(nameof(Mine));
        }


        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {

            return RedirectToAction(nameof(Mine));
        }




    }
}

HouseRentingSystem/Views/Agent/Become.cshtml
@model BecomeAgentFormModel
@{
    ViewBag.Title = "Become Agent";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />
@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"] != null)
{
    <div class="alert alert-danger" role="alert"> @ViewData.ModelState["Error"].Errors.First().ErrorMessage </div>
}
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" placeholder="+359888888888">
                <span asp-validation-for="PhoneNumber" class="small text-danger"></span>
            </div>
            <div class="text-center"> <input class="btn btn-primary mt-3 " type="submit" value="Save" /> </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HouseRentingSystem/Views/Home/Index.cshtml
@model IEnumerable<HouseIndexServiceModel>
@{
    ViewData["Title"] = "Home Page"; var houses = Model.ToList();
} @if (!houses.Any())
{
    <div class="mt-4 p-5 bg-light">
        <h1 class="display-4">Welcome to the best place for renting houses!</h1>
        <p class="lead"> There are no houses in the system currently available so why don't you just add one? </p>
        <hr class="my-4"> <p class="lead">
            @if (User?.Identity?.IsAuthenticated ?? false)
            {
                <a asp-controller="House" asp-action="Add" class="btn btn-primary btn-lg" role="button">Add House</a>
            }
        </p>
    </div>
}

<div class="mb-5"></div>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @for (int i = 0; i < houses.Count(); i++)
        {
            var house = houses[i];
            <div class="carousel-item @(i == 0 ? "active" : string.Empty)">
                <img class="d-block w-100" style="height:500px" src="@house.ImageUrl" alt="@house.Title">

                <div class="carousel-caption d-none d-md-block">
                    <h5>
                        <a class="btn btn-primary" asp-controller="House" asp-action="Details" asp-route-id="@house.Id"> @house.Title</a>
                    </h5>
                </div>
            </div>
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

HouseRentingSystem/Views/House/Add.cshtml
@model HouseFormModel

@{
    ViewBag.Title = "Add House";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />

<partial name="_HouseFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HouseRentingSystem/Views/House/All.cshtml
@model AllHousesQueryModel

@{
    ViewBag.Title = "All Houses";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />

HouseRentingSystem/Views/House/Delete.cshtml
@model HouseDetailsViewModel

@{
    ViewBag.Title = "Delete Houses";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />

HouseRentingSystem/Views/House/Details.cshtml
@model HouseDetailsViewModel

@{
    ViewBag.Title = "House Details";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />

HouseRentingSystem/Views/House/Edit.cshtml
@model HouseFormModel

@{
    ViewBag.Title = "Edit Houses";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />

HouseRentingSystem/Views/House/Mine.cshtml
@model AllHousesQueryModel

@{
    ViewBag.Title = "My Houses";
}
<h2 class="text-center">@ViewBag.Title</h2>
<h2 />

HouseRentingSystem/Views/Shared/Components/MainMenuComponent/Default.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="All">All Houses</a>
    </li>
    @if (this.User?.Identity?.IsAuthenticated ?? false)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Mine">My Houses</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Add">Add House</a>
        </li>
    }
</ul>

HouseRentingSystem/Views/Shared/_HouseFormPartial.cshtml
@model HouseFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" placeholder="Title...">
                <span asp-validation-for="Title" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" placeholder="Address...">
                <span asp-validation-for="Address" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label> <textarea asp-for="Description" rows="4" class="form-control" placeholder="Two bedrooms..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div> <div class="form-group">
                <label asp-for="ImageUrl"></label> <input asp-for="ImageUrl" class="form-control" placeholder="Your fine UR

                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div> <div class="form-group">
                <label asp-for="PricePerMonth"></label>
                <input asp-for="PricePerMonth" class="form-control"> <span asp-validation-for="PricePerMonth" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div> <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

HouseRentingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Best House Renting System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HouseRentingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">House Renting WorldWide</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(MainMenuComponent))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - HouseRentingSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>